version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartleader_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ../front-end
      dockerfile: Dockerfile
    container_name: smartleader_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - laravel
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: smartleader_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: smartleader
      MYSQL_USER: smartleader
      MYSQL_PASSWORD: smartleader
      MYSQL_ROOT_PASSWORD: smartleader
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: smartleader_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - laravel

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartleader_queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - app
      - redis
      - mysql

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
